version: '3.8'

services:
  # React App
  react-app:
    container_name: my-react-app
    image: node:latest
    working_dir: /latest
    volumes:
      - ./app/my-app:/app
    environment:
      - NODE_ENV=development
    command: npm start 
    ports:
      - "3000:3000"