version: '3.8'

services:
  # React App
  react-app:
    container_name: my-react-app
    image: node:latest
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"