name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and start containers
        run: |
          docker-compose -f ./docker-compose.yml up -d
          docker-compose -f ./docker-compose.yml ps
          sleep 30  # Wait for containers to start

      - name: Run npm test inside container
        run: |
          timeout 300s docker exec my-react-app sh -c "cd /app && npm install && npm test"



      - name: Stop and remove containers
        run: |
          docker-compose -f ./docker-compose.yml down

